/*
 * InterruptHAL.h
 *
 *  Created on: Mar 30, 2021
 *      Author: Matthew Zhong
 *  Supervisor: Leyla Nazhandali
 */

#ifndef INTERRUPTHAL_H_
#define INTERRUPTHAL_H_

#include <stdbool.h>

/** The master initialization function. Call this in your main. */
void Init_InterruptHal(void);

/* -------------------------------------------------------------------------- */
/* Light-weight LED functions. Use these instead of the old LED structs to    */
/* turn on and turn off any LEDs you need. If you need more LEDs, write more  */
/* functions for the LEDs you need.                                           */
/*                                                                            */
/* For reasons that will become readily apparent as you play with TIMER_A and */
/* read the datasheets avaiable to you, we advise you to avoid using the      */
/* Boosterpack LEDs and to stick with using just the ones on the Launchpad.   */
/* -------------------------------------------------------------------------- */
void LaunchpadLED1_TurnOn(void);
void LaunchpadLED2_TurnOn(void);

void LaunchpadLED1_TurnOff(void);
void LaunchpadLED2_TurnOff(void);

void LaunchpadLED1_Toggle(void);
void LaunchpadLED2_Toggle(void);

/** Retrieves the most recent event(s) generated by a relevant ISR. */
bool LaunchpadS1_Tapped(void);
bool BoosterpackJS_Tapped(void);

/** Resets all interrupt event flags, then puts the microcontroller to sleep. */
void SleepProcessor(void);

#endif /* INTERRUPTHAL_H_ */
